version: '3'
services:
  zookeeper:
    build: zookeeper/
    container_name: zookeeper
    hostname: zookeeper
    domainname: confluent.local
    restart: on-failure
    volumes:
      - ./certs/:/var/lib/secret
    networks:
      default:
        aliases:
          - zookeeper.confluent.local


  kafka:
    build: kafka/
    container_name: kafka
    hostname: kafka
    domainname: confluent.local
    depends_on: 
      - zookeeper
    restart: on-failure
    volumes:
      - ./certs/:/var/lib/secret
    networks:
      default:
        aliases:
          - kafka.confluent.local

  schema-registry:
    build: schema-registry/
    container_name: schema-registry
    hostname: schema-registry
    domainname: confluent.local
    depends_on: 
      - kafka
    restart: on-failure
    volumes:
      - ./certs/:/var/lib/secret
      - ./schema-registry/schema-registry.properties:/etc/schema-registry/schema-registry.properties
    networks:
      default:
        aliases:
          - schema-registry.confluent.local
    ports:
      - "8081:8081"

volumes:
  secret: {}

networks:
  default:
