FROM kerberos-demo/kafka-base

COPY server.properties /etc/kafka/server.properties
COPY kafka.sasl.jaas.config /etc/kafka/kafka_server_jaas.conf

#EXPOSE 9093
#
#CMD kafka-server-start /etc/kafka/server.properties
