#!/usr/bin/env bash

docker-compose up -d


echo "How to handle ACLs:"
echo ""
echo "List all existing ACLs"
echo "$> docker-compose exec schema-registry sr-acl-cli --config ./etc/schema-registry/schema-registry.properties --list"
echo "Add write access to subject test-subject-value for user Bob"
echo "$> docker-compose exec schema-registry sr-acl-cli --config ./etc/schema-registry/schema-registry.properties --add -s test-subject-value -p Bob -o SUBJECT_WRITE"
echo "Add an admin user"
echo "$> docker-compose exec schema-registry sr-acl-cli --config ./etc/schema-registry/schema-registry.properties --add -s * -p schema-admin -o *"
echo "Remove write access to subject test-subject-value for user Bob"
echo "$> docker-compose exec schema-registry sr-acl-cli --config ./etc/schema-registry/schema-registry.properties --remove -s test-subject-value -p Bob -o SUBJECT_WRITE"
