version: '3'
services:

  zookeeper:
    build: zookeeper/
    container_name: zookeeper
    hostname: zookeeper
<<<<<<< HEAD
    # restart: on-failure
    #    environment:
    #  - KAFKA_OPTS=-Djava.security.auth.login.config=/etc/kafka/zookeeper_server_jaas.conf 
=======
>>>>>>> Dabz-master

  kafka:
    build: kafka/
    container_name: kafka
    environment:
      - KAFKA_OPTS=-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf 
    depends_on: 
      - zookeeper
