#!/bin/sh

docker-compose up -d

echo "Example configuration:"
echo "-> kafka-console-producer --broker-list localhost:9093 --producer.config producer.properties --topic test"
echo "-> kafka-console-consumer --bootstrap-server localhost:9093 --consumer.config consumer.properties --topic test --from-beginning"
