version: '3.4'

services:
  zookeeper:
    image: ${REPOSITORY}/cp-zookeeper:${TAG}
    container_name: zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_AUTH_PROVIDER_SASL: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
      KAFKA_OPTS: -Djava.security.auth.login.config=/tmp/zookeeper.sasl.jaas.config
    volumes:
        - $PWD/zookeeper.sasl.jaas.config:/tmp/zookeeper.sasl.jaas.config

  kafka:
    image: ${REPOSITORY}/cp-kafka:${TAG}
    container_name: kafka
    hostname: kafka
    ports:
        - "9093:9093"
    environment:
        KAFKA_OPTS: -Djava.security.auth.login.config=/tmp/kafka.sasl.jaas.config
        KAFKA_SUPER_USERS: User:admin,User:kafka
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9093
        KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9093
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SASL_PLAINTEXT,OUTSIDE:SASL_PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-256
        KAFKA_LISTENER_NAME_INTERNAL_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256
        KAFKA_LISTENER_NAME_OUTSIDE_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256

        KAFKA_LISTENER_NAME_INTERNAL_SCRAM__SHA__256_SASL_JAAS_CONFIG:    org.apache.kafka.common.security.scram.ScramLoginModule required \
                                                              username="admin" \
                                                              password="admin-secret" ;
        KAFKA_LISTENER_NAME_OUTSIDE_SCRAM__SHA__256_SASL_JAAS_CONFIG:   org.apache.kafka.common.security.scram.ScramLoginModule required \
                                                              username="admin" \
                                                              password="admin-secret" ;
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1        
    volumes:
        - $PWD/kafka.sasl.jaas.config:/tmp/kafka.sasl.jaas.config
    depends_on: 
      - zookeeper
