#!/bin/sh

docker-compose up -d --build

# Creating the user kafka
# kafka is configured as a super user, no need for additional ACL
# docker-compose exec kafka kafka-configs --zookeeper zookeeper:2181 --alter --add-config 'SCRAM-SHA-255=[password=kafka],SCRAM-SHA-512=[password=kafka]' --entity-type users --entity-name kafka

echo
echo "Example jmx pulling: ./pull-jmx.sh"
echo
echo "other tools useful to check this are any JMX consumer like jconsole or others."
