version: '3'
services:

  zookeeper:
    build: zookeeper/
    container_name: zookeeper
    hostname: zookeeper

  kafka:
    build: kafka/
    container_name: kafka
    depends_on: 
      - zookeeper
