#!/bin/sh

docker-compose up -d

# Creating the user kafka
# kafka is configured as a super user, no need for additional ACL
# docker-compose exec kafka kafka-configs --zookeeper zookeeper:2181 --alter --add-config 'SCRAM-SHA-255=[password=kafka],SCRAM-SHA-512=[password=kafka]' --entity-type users --entity-name kafka

echo "Example configuration:"
echo "-> docker-compose exec kafka kafka-console-producer --broker-list kafka:9092 --topic test"
echo "-> docker-compose exec kafka kafka-console-consumer --bootstrap-server kafka:9092 --topic test --from-beginning"
