version: '3'
services:

  zookeeper:
    build: zookeeper/
    container_name: zookeeper
    hostname: zookeeper

  kafka:
    build: kafka/
    container_name: kafka
    depends_on: 
      - zookeeper
    environment:
      - KAFKA_OPTS=-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf

