version: '3.5'
services:
  kdc:
    build: kdc/
    hostname: kdc
    domainname: kerberos_default
    networks:
      - kerberos_default

    container_name: kdc
    volumes:
      - secret:/var/lib/secret
      - ./kdc/krb5.conf:/etc/kdc/krb5.conf

  zookeeper1:
    build: zookeeper1/
    container_name: zookeeper1
    hostname: zookeeper1
    domainname: kerberos_default
    networks:
      - kerberos_default

    depends_on:
      - kdc
    # Required to wait for the keytab to get generated
    restart: on-failure
    environment:
      - KAFKA_OPTS=-Djava.security.auth.login.config=/etc/kafka/zookeeper_server_jaas.conf
    volumes:
      - secret:/var/lib/secret
      - ./kdc/krb5.conf:/etc/krb5.conf

  kafka1:
    build: kafka1/
    container_name: kafka1
    hostname: kafka1
    domainname: kerberos_default
    networks:
      - kerberos_default
    environment:
      - KAFKA_OPTS=-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf
    depends_on:
      - zookeeper1
      - kdc
    # Required to wait for the keytab to get generated
    restart: on-failure
    volumes:
      - secret:/var/lib/secret
      - ./kdc/krb5.conf:/etc/krb5.conf
    command: "sleep infinity"

  client:
    build: client/
    container_name: client
    hostname: client
    domainname: kerberos_default
    networks:
      - kerberos_default
    environment:
      - KAFKA_OPTS=-Djava.security.auth.login.config=/etc/kafka/client_jaas.conf
    depends_on:
      - kafka1
      - kdc
    # Required to wait for the keytab to get generated
    volumes:
      - secret:/var/lib/secret
      - ./kdc/krb5.conf:/etc/krb5.conf



  kafkacat:
    image: confluentinc/cp-kafkacat
    container_name: kafkacat
    hostname: kafkacat
    domainname: kerberos_default
    networks:
      - kerberos_default
    environment:
      - KAFKA_OPTS=-Djava.security.auth.login.config=/etc/kafka/client_jaas.conf
    depends_on:
      - kafka1
      - kdc
    # Required to wait for the keytab to get generated
    volumes:
      - secret:/var/lib/secret
      - ./kdc/krb5.conf:/etc/krb5.conf
    command: "sleep infinity"

volumes:
  secret: {}

networks:
  kerberos_default:
    name: kerberos_default
