version: '3.5'
services:
  kdc:
    hostname: kdc.kerberos-demo.local
    #domainname: kerberos_default
    build: kdc/
    container_name: kdc
    volumes:
      - secret:/var/lib/secret
      - ./kdc/krb5.conf:/etc/kdc/krb5.conf

  zookeeper:
    build: zookeeper/
    container_name: zookeeper
    hostname: zookeeper.kerberos-demo.local
    #domainname: kerberos_default
    depends_on:
      - kdc
    # Required to wait for the keytab to get generated
    restart: on-failure
    volumes:
      - secret:/var/lib/secret
      - ./kdc/krb5.conf:/etc/krb5.conf

  kafka:
    build: kafka/
    container_name: kafka
    hostname: kafka.kerberos-demo.local
    #domainname: kerberos_default
    depends_on:
      - zookeeper
      - kdc
    # Required to wait for the keytab to get generated
    restart: on-failure
    volumes:
      - secret:/var/lib/secret
      - ./kdc/krb5.conf:/etc/krb5.conf

  client:
    build: client/
    container_name: client
    hostname: client.kerberos-demo.local
    #domainname: kerberos_default
    depends_on:
      - kafka
      - kdc
    # Required to wait for the keytab to get generated
    volumes:
      - secret:/var/lib/secret
      - ./kdc/krb5.conf:/etc/krb5.conf

volumes:
  secret: {}

networks:
  default:
    name: kerberos-demo.local
