version: '3.8'

services:
  zookeeper-source:
    image: ${REPOSITORY}/cp-zookeeper:${TAG}
    container_name: zookeeper-source
    hostname: zookeeper-source
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_AUTH_PROVIDER_SASL: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
      KAFKA_OPTS: -Djava.security.auth.login.config=/tmp/zookeeper.sasl.jaas.config
    volumes:
        - ./zookeeper.sasl.jaas.config:/tmp/zookeeper.sasl.jaas.config
        - ./kafka.sasl.jaas.config:/tmp/kafka.sasl.jaas.config
        - ./jline-2.14.6.jar:/usr/share/java/kafka/jline-2.14.6.jar

  kafka-source:
    image: ${REPOSITORY}/cp-kafka:${TAG}
    container_name: kafka-source
    hostname: kafka-source
    ports:
        - "9093:9093"
    environment:
        KAFKA_OPTS: -Djava.security.auth.login.config=/tmp/kafka.sasl.jaas.config
        KAFKA_SUPER_USERS: User:admin;User:kafka
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-source:2181'
        KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9093
        KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-source:9092,OUTSIDE://localhost:9093
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SASL_PLAINTEXT,OUTSIDE:SASL_PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-256
        KAFKA_LISTENER_NAME_INTERNAL_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256
        KAFKA_LISTENER_NAME_OUTSIDE_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256

        KAFKA_LISTENER_NAME_INTERNAL_SCRAM___SHA___256_SASL_JAAS_CONFIG:    org.apache.kafka.common.security.scram.ScramLoginModule required \
                                                              username="admin" \
                                                              password="admin-secret" ;
        KAFKA_LISTENER_NAME_OUTSIDE_SCRAM___SHA___256_SASL_JAAS_CONFIG:   org.apache.kafka.common.security.scram.ScramLoginModule required \
                                                              username="admin" \
                                                              password="admin-secret" ;
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
        - ./kafka.sasl.jaas.config:/tmp/kafka.sasl.jaas.config
        - ./cluster-source.properties:/tmp/cluster-source.properties
        - ./admin.properties:/tmp/admin.properties

    depends_on:
      - zookeeper-source


  zookeeper-destination:
    image: ${REPOSITORY}/cp-zookeeper:${TAG}
    container_name: zookeeper-destination
    hostname: zookeeper-destination
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_AUTH_PROVIDER_SASL: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
      KAFKA_OPTS: -Djava.security.auth.login.config=/tmp/zookeeper.sasl.jaas.config
    volumes:
        - ./zookeeper.sasl.jaas.config:/tmp/zookeeper.sasl.jaas.config
        - ./kafka.sasl.jaas.config:/tmp/kafka.sasl.jaas.config
        - ./jline-2.14.6.jar:/usr/share/java/kafka/jline-2.14.6.jar

  kafka-destination:
    image: ${REPOSITORY}/cp-server:${TAG}
    container_name: kafka-destination
    hostname: kafka-destination
    ports:
        - "9094:9094"
    environment:
        KAFKA_OPTS: -Djava.security.auth.login.config=/tmp/kafka.sasl.jaas.config
        KAFKA_SUPER_USERS: User:admin;User:kafka
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-destination:2181'
        KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
        KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-destination:9092,OUTSIDE://localhost:9094
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SASL_PLAINTEXT,OUTSIDE:SASL_PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-256
        KAFKA_LISTENER_NAME_INTERNAL_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256
        KAFKA_PASSWORD_ENCODER_SECRET: frankBGdu39
        KAFKA_LISTENER_NAME_OUTSIDE_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256

        KAFKA_LISTENER_NAME_INTERNAL_SCRAM___SHA___256_SASL_JAAS_CONFIG:    org.apache.kafka.common.security.scram.ScramLoginModule required \
                                                              username="admin" \
                                                              password="admin-secret" ;
        KAFKA_LISTENER_NAME_OUTSIDE_SCRAM___SHA___256_SASL_JAAS_CONFIG:   org.apache.kafka.common.security.scram.ScramLoginModule required \
                                                              username="admin" \
                                                              password="admin-secret" ;
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_CONFLUENT_CLUSTER_LINK_ENABLE: "true"
    volumes:
        - ./kafka.sasl.jaas.config:/tmp/kafka.sasl.jaas.config
        - ./cluster-source.properties:/tmp/cluster-source.properties
        - ./cluster-destination.properties:/tmp/cluster-destination.properties
        - ./admin.properties:/tmp/admin.properties

    depends_on:
      - zookeeper-destination
